name: dev-spree-ecomprocessing-plugin
services:
  spree-app:
    tty: true
    stdin_open: true
    build:
      target: development
    environment:
      - RAILS_ENV=development
    volumes:
      - ${PLUGIN_SOURCE}:/mnt/spree-ecomprocessing-plugin
